### ISSUE TITLE
Do we have to support Windows?

### ISSUE THREAD

**Issue by sargun** [containerd/continuity#119]
Why do we have to support Windows? IT seems like a waste of time.

**Comment by dmcgowan** [comment]
Because people use Windows containers and Windows containers use filesystems. If we are finding something is too hard to support for Windows, it is probably best to take a step back and see if we are doing something wrong or haven't created the right interfaces.

**Comment by TBBle** [comment]
Dropping Windows support from containerd/continuity would certainly simply the answers to #174 and #179 as "Just don't use containerd/continuity for the containerd/containerd snapshot suite"...

**Comment by kzys** [comment]
containerd has been using continuity on Windows. While Windows is relatively different from other Unix variants, the ship has sailed already :)
