### ISSUE TITLE
Use ioctl_ficlonerange(2) instead of copy_file_range(2)

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/continuity#126]
> The `cp --reflink` command uses [the `FICLONERANGE` `ioctl()` command](http://man7.org/linux/man-pages/man2/ioctl_ficlonerange.2.html), but not [`copy_file_range()`](http://man7.org/linux/man-pages/man2/copy_file_range.2.html); in fact, no utilities use `copy_file_range()`, though it should be the default.

https://lwn.net/Articles/754506/

And there is also [`ioctl_fideduperange(2`](http://man7.org/linux/man-pages/man2/ioctl_fideduperange.2.html). really confusing.. :(

**Comment by stevvooe** [comment]
Why? Are you suggesting we change? It sounds like containerd makes the correct choice over `cp`.

**Comment by AkihiroSuda** [comment]
Does current containerd really dedupe?

**Comment by AkihiroSuda** [comment]
Actually, deduplication seems not working with the current implementation
https://github.com/AkihiroSuda/continuity/commit/086786067f93756110527e4f94d642ead63a13af

**Comment by AkihiroSuda** [comment]
Sorry copy_file_range seems actually doing reflink (at least on XFS): https://github.com/containerd/continuity/pull/128

**Comment by AkihiroSuda** [comment]
But it looks like potentially there is case where `copy_file_range` does not do deduplication while `ioctl_ficlonerange`  does, on some non-XFS filesystems?

https://twitter.com/lordcyphar/status/1039417947033194496
