### ISSUE TITLE
How many Go versions in Travis?

### ISSUE THREAD

**Issue by estesp** [containerd/continuity#132]
Right now we are testing 1.8, 1.9, 1.10, 1.11, and tip via Travis, across 3 platforms; so 15 travis runs for each PR. Not a big deal if we want to maintain compatibility back that far, but none of our other projects seem to have that breadth of coverage.

@containerd/containerd-maintainers

**Comment by mikebrow** [comment]
don't need that much for each pr, but it would be nice to test a bucket of them once a day I suppose. Suggest 1.10.x (till we push a the next major release) then move up to 1.11.x. Then a daily bucket that tests them all for go version dependencies.

**Comment by estesp** [comment]
irrelevant now that we are on GitHub Actions
