### ISSUE TITLE
Errophone auto-generated constants, for Go standard library (gollvm)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [containerd/continuity#162]
Hi.
Cross-posting the bug, which is tracked during build progress for [cri-o ](https://github.com/cri-o/cri-o/issues/4197) : 

    

> github.com/containerd/continuity/fs
>     mkdir -p $WORK/b407/
>     cd $WORK
>     /usr/local/bin/llvm-goc -fgo-importcfg=/dev/null -c -x c - -o /dev/null || true
>     mkdir -p $WORK/b407/importcfgroot/github.com/containerd/continuity
>     ln -s /home/oceanfish81/.cache/go-build/01/0149872ebed362b2db5d5cb500fe4c36dc53aa0eeaf43445d2a1d57f87797f22-d $WORK/b407/importcfgroot/github.com/containerd/continuity/libsysx.a
>     mkdir -p $WORK/b407/importcfgroot/github.com/pkg
>     ln -s /home/oceanfish81/.cache/go-build/5c/5c5c0c7d8f5175eae2b4d2a083bbfa586296699b6d6e847a6034fb77f0283e5b-d $WORK/b407/importcfgroot/github.com/pkg/liberrors.a
>     mkdir -p $WORK/b407/importcfgroot/github.com/sirupsen
>     ln -s /home/oceanfish81/.cache/go-build/92/92e22833f5517c1584404320f391ae330ef4ec12a7ee701ea0863735c4e5a39e-d $WORK/b407/importcfgroot/github.com/sirupsen/liblogrus.a
>     mkdir -p $WORK/b407/importcfgroot/golang.org/x/sync
>     ln -s /home/oceanfish81/.cache/go-build/b4/b4dade4823a139177beb6326f044ad405152a51915db5eff2d1f1100f377d538-d $WORK/b407/importcfgroot/golang.org/x/sync/liberrgroup.a
>     mkdir -p $WORK/b407/importcfgroot/golang.org/x/sys
>     ln -s /home/oceanfish81/.cache/go-build/79/79581a3b9031e51313108a803ec4be9cd5e789dcf66ef4dbe3af40cfbd47664a-d $WORK/b407/importcfgroot/golang.org/x/sys/libunix.a
>     cd /home/oceanfish81/cri-o/vendor/github.com/containerd/continuity/fs
>     /usr/local/bin/llvm-goc -c -O2 -g -m64 -fdebug-prefix-map=$WORK=/tmp/go-build -gno-record-gcc-switches -fgo-pkgpath=github.com/containerd/continuity/fs -o $WORK/b407/go.o -I $WORK/b407/importcfgroot ./copy.go ./copy_linux.go ./diff.go ./diff_unix.go ./dtype_linux.go ./du.go ./du_unix.go ./hardlink.go ./hardlink_unix.go ./path.go ./stat_linuxopenbsd.go ./time.go
>     github.com/containerd/continuity/fs
>     vendor/github.com/containerd/continuity/fs/dtype_linux.go:61:26:
> 
> error: reference to undefined identifier 'syscall.DT_UNKNOWN'

Is it possible to rule out the cause of this, by expressing the algorithm without the usage of a pre-compiled constant (to calculate in another way) ?

Ivan

**Comment by advancedwebdeveloper** [comment]
CC @cpuguy83 @zhsj @AkihiroSuda @poizan42 @nixpanic @estesp

**Comment by zhsj** [comment]
https://github.com/golang/go/issues/41404 it says it's fixed in libgo.
