### ISSUE TITLE
Support ctime and mtime

### ISSUE THREAD

**Issue by aaronlehmann** [containerd/continuity#30]
Continuity should capture ctime (file creation timestamp) and mtime (file modification timestamp) in manifests, and by default, it should apply and verify these properties.

In case a particular application of Continuity needs to be insensitive to creation or modification times, it should be possible to use `--ignore-attr` at verify or apply time to exclude these attributes (see #27).

**Comment by AkihiroSuda** [comment]
Seems dupe of #16
